[package]
name = "rusty-essay-editor"
version = "0.1.0"
edition = "2024"

[dependencies]
# async-tungstenite = { version = "0.29.1", features = ["gio-runtime"] }
async-tungstenite = { path = "../async-tungstenite", features = [
    "gio-runtime",
] }
automerge = "0.6.1"
futures = "0.3.31"
gio = "0.20.12"
glib = "0.20.12"
gtk = { version = "0.9.7", package = "gtk4", features = ["v4_16"] }
samod = { path = "../samod/samod", features = ["gio", "tungstenite"] }
sourceview5 = "0.9.1"

tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
